if: tag IS blank

language: node_js

node_js:
  - v10

cache:
  yarn: true

# before_install:
#   - yarn global add lerna

install:
  - npm ci

script:
  - yarn lint
  - yarn flow-typed-install
  - yarn flow
  - yarn test -- --coverage

before_deploy:
  - yarn build
  - yarn build-storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: storybook-static
  on:
    branch: master

after_script:
  - yarn codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)